apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: file-server
        image: neeraj010702/zip-server:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /data/files
      volumes:
      - name: data-volume
        hostPath:
          path: /mnt/c/Users/Public/Downloads/DATA_Files
          type: Directory
