pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('neeraj010702/zip-server:latest')
                }
            }
        }

        stage('Load Image into Minikube') {
            steps {
                bat 'minikube image load neeraj010702/zip-server:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat 'kubectl apply -f manifests/deployment-1.yaml'
                bat 'kubectl apply -f manifests/service.yaml'
                bat 'kubectl rollout restart deployment file-server'
            }
        }
    }
}
